services:
  - type: web
    name: mabrig-backend
    runtime: node
    rootDir: mabrig-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYSTACK_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://mabrigresearch.online
